"""empty message

Revision ID: 2e8bc3267636
Revises: 412a482d8bea
Create Date: 2015-07-26 14:51:01.585354

"""

# revision identifiers, used by Alembic.
revision = '2e8bc3267636'
down_revision = '412a482d8bea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('name', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'name')
    ### end Alembic commands ###
