"""empty message

Revision ID: 412a482d8bea
Revises: 4cff46766078
Create Date: 2015-07-26 14:05:20.945497

"""

# revision identifiers, used by Alembic.
revision = '412a482d8bea'
down_revision = '4cff46766078'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    ### end Alembic commands ###
