"""empty message

Revision ID: 4cf8a1f64235
Revises: f94ec25d046
Create Date: 2015-08-27 18:43:15.118000

"""

# revision identifiers, used by Alembic.
revision = '4cf8a1f64235'
down_revision = 'f94ec25d046'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('predicate', sa.String(length=128), nullable=True),
    sa.Column('object', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_meta')
    ### end Alembic commands ###
